### ISSUE TITLE
Prifddinas southeastern rock never shows up in the plugin

### ISSUE THREAD

**Issue by deepmouse** [TheStonedTurtle/RuniteRocks#1]
![Capture](https://user-images.githubusercontent.com/39153505/87170615-3ff68100-c2da-11ea-8c5b-081aa1ffc19a.PNG)

As you can see, the SE runite rock is available, but it does not show up as available in the plugin. That rock also doesn't show up on any other world in the list either

**Comment by TheStonedTurtle** [comment]
This has been fixed in commit 058f348695863d2a975ac21cb389a759df0c4b3a and will be available once [v1.2 has been merged](https://github.com/runelite/plugin-hub/pull/455)

**Comment by deepmouse** [comment]
Thank you! Good job on the plugin, love it <3
