### ISSUE TITLE
Respawn timers do not get triggered when runite ore is depleted

### ISSUE THREAD

**Issue by kdefries** [TheStonedTurtle/RuniteRocks#2]
Whenever I 'witness depletion' of an ore, the respawn timer stays at 'available' and never starts counting down. I noticed the 'last visit' tab gets updated whenever a runite ore respawns and gets depleted. However, the actual respawn timer never gets updated.

This happens with the default configuration settings, whenever I check the box 'ignore inaccurate' nothing is ever even shown.

**Comment by TheStonedTurtle** [comment]
Can you tell me which rock(s) in particular this happens too? I just tested this at the Prif mine and witnessing and depletion causes the `Respawn` category to start counting down.

**Comment by kdefries** [comment]
> Can you tell me which rock(s) in particular this happens too? I just tested this at the Prif mine and witnessing the depletion causes the `Respawn` category to start counting down.

I have this issue in the mining guild, for both rocks. I haven't been able to test this elsewhere.

**Comment by TheStonedTurtle** [comment]
Sorry for taking so long to fix this issue, Got busy IRL and forgot about this issue. The tracking for the rocks inside the Mining Guild have been fixed in commit 90721d95be34a480adb82543e3762059f1a4ccbd and will be available in v1.2.1
